version: 2.1

jobs:
  build:
    docker:
      - image: simple-node
        auth:
          username: saegeroliver
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

workflows:
  build:
    jobs:
      - build