version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: "Test Echo"
          command: echo "test"

      - run:
          name: "Build docker image"
          command: docker build -t saegeroliver/simple-node:latest .

      - run:
          name: "Push docker image to hub"
          command: docker push saegeroliver/simple-node:latest

workflows:
  build-and-deploy:
    jobs:
      - build